# Generated by Django 4.1 on 2023-03-21 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippet_app', '0005_alter_lang_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='lang',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet_app.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet_app.lang'),
        ),
    ]
